"""Compatibility facade for SQLite storage helpers.

The implementation is split behind storage-specific import surfaces while this
module keeps existing imports working during the cleanup.
"""

from app.storage._sqlite_impl import *  # noqa: F401,F403

__all__ = [
    "ClearPlan",
    "ClearScope",
    "DEFAULT_DB_PATH",
    "DEFAULT_EXPLORED_CAPACITY",
    "DEFAULT_RANKED_CAPACITY",
    "DEFAULT_SCORING_PRESET_ID",
    "DEFAULT_UNRANKED_CAPACITY",
    "ExplorationMetadata",
    "ExploredOfferRecord",
    "PruneStats",
    "StorageCounts",
    "StoredOffer",
    "UpsertStats",
    "VALID_CLEAR_SCOPES",
    "VALID_REVIEW_STATUSES",
    "clear_data",
    "clear_rankings",
    "create_ranking_run",
    "exclude_existing_offers",
    "find_existing_offer_id",
    "find_existing_offer_id_by_url",
    "find_existing_offer_ids_batch",
    "find_existing_offer_ids_by_url_batch",
    "find_screening_result_id",
    "get_clear_plan",
    "get_exploration_metadata",
    "get_review_filter_options",
    "get_scoring_preset",
    "get_storage_counts",
    "has_explored_offer",
    "has_explored_offers_batch",
    "init_db",
    "list_ai_reviews",
    "list_explored_offers",
    "list_offer_locations",
    "list_ranked_offers",
    "list_scoring_presets",
    "list_screened_offers",
    "list_screening_results",
    "list_unranked_review_offers",
    "open_connection",
    "prune_storage",
    "record_explored_job",
    "record_explored_jobs_batch",
    "record_explored_offer",
    "save_ai_review",
    "save_exploration_metadata",
    "save_offer_score",
    "save_offer_scores",
    "save_offer_scores_batch",
    "save_ranking",
    "save_screening_result",
    "save_screening_results_batch",
    "select_screened_offers",
    "select_unranked_offers",
    "update_offer_status",
    "upsert_offers",
    "upsert_offers_batch",
]
